
platform :ios, '8.0'
use_frameworks!

def pods
   pod 'AFNetworking', '~> 3.1.0'
   pod 'Masonry'
   pod 'MBProgressHUD'
   pod 'SDWebImage', '~>  4.4.2'
   pod 'MJRefresh'
   pod 'Bugly'
   pod 'WechatOpenSDK', '~> 1.8.2'
   pod 'AMapLocation'
   pod 'MLLabel'
   pod 'MMWebView'
   pod 'UUButton'
   pod 'JPush'
   pod 'UMCCommon', '~> 1.5.2'
   pod 'UMCAnalytics', '~> 5.5.0'
   pod 'RongCloudIM/IMLib', '2.9.3'
   pod 'RongCloudIM/IMKit', '2.9.3'
   pod 'JQFMDB'
   pod 'CTAssetsPickerController'
   pod 'IQKeyboardManager'
   pod 'MJExtension'

end

target :'bissc' do
    pods
end

#pod 'VehicleKeyboard-swift', '~> 0.9.5'
#LTScrollView
